const PLAN_CATALOG = {
  // STARTER (Escovia: Club)
  starter_7: {
    internalPlanType: "club",
    neutralPlanCode: "starter_7",
    durationDays: 7,
    amount: 29,
    currency: "chf",
    stripeLabel: "Digital visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  starter_15: {
    internalPlanType: "club",
    neutralPlanCode: "starter_15",
    durationDays: 15,
    amount: 49,
    currency: "chf",
    stripeLabel: "Digital visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  starter_20: {
    internalPlanType: "club",
    neutralPlanCode: "starter_20",
    durationDays: 20,
    amount: 59,
    currency: "chf",
    stripeLabel: "Digital visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  starter_30: {
    internalPlanType: "club",
    neutralPlanCode: "starter_30",
    durationDays: 30,
    amount: 89,
    currency: "chf",
    stripeLabel: "Digital visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  starter_60: {
    internalPlanType: "club",
    neutralPlanCode: "starter_60",
    durationDays: 60,
    amount: 169,
    currency: "chf",
    stripeLabel: "Digital visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  starter_90: {
    internalPlanType: "club",
    neutralPlanCode: "starter_90",
    durationDays: 90,
    amount: 239,
    currency: "chf",
    stripeLabel: "Digital visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  starter_180: {
    internalPlanType: "club",
    neutralPlanCode: "starter_180",
    durationDays: 180,
    amount: 449,
    currency: "chf",
    stripeLabel: "Digital visibility package",
    stripeDescription: "Online promotion and visibility service",
  },

  // GROWTH (Escovia: Privilege)
  growth_7: {
    internalPlanType: "privilege",
    neutralPlanCode: "growth_7",
    durationDays: 7,
    amount: 79,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  growth_10: {
    internalPlanType: "privilege",
    neutralPlanCode: "growth_10",
    durationDays: 10,
    amount: 99,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  growth_15: {
    internalPlanType: "privilege",
    neutralPlanCode: "growth_15",
    durationDays: 15,
    amount: 139,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  growth_20: {
    internalPlanType: "privilege",
    neutralPlanCode: "growth_20",
    durationDays: 20,
    amount: 169,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  growth_30: {
    internalPlanType: "privilege",
    neutralPlanCode: "growth_30",
    durationDays: 30,
    amount: 189,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  growth_60: {
    internalPlanType: "privilege",
    neutralPlanCode: "growth_60",
    durationDays: 60,
    amount: 349,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  growth_90: {
    internalPlanType: "privilege",
    neutralPlanCode: "growth_90",
    durationDays: 90,
    amount: 499,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },

  // ADVANCED (Escovia: Elite)
  advanced_3: {
    internalPlanType: "elite",
    neutralPlanCode: "advanced_3",
    durationDays: 3,
    amount: 79,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  advanced_5: {
    internalPlanType: "elite",
    neutralPlanCode: "advanced_5",
    durationDays: 5,
    amount: 99,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  advanced_7: {
    internalPlanType: "elite",
    neutralPlanCode: "advanced_7",
    durationDays: 7,
    amount: 129,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  advanced_10: {
    internalPlanType: "elite",
    neutralPlanCode: "advanced_10",
    durationDays: 10,
    amount: 149,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  advanced_15: {
    internalPlanType: "elite",
    neutralPlanCode: "advanced_15",
    durationDays: 15,
    amount: 179,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  advanced_20: {
    internalPlanType: "elite",
    neutralPlanCode: "advanced_20",
    durationDays: 20,
    amount: 209,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  advanced_30: {
    internalPlanType: "elite",
    neutralPlanCode: "advanced_30",
    durationDays: 30,
    amount: 249,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  advanced_60: {
    internalPlanType: "elite",
    neutralPlanCode: "advanced_60",
    durationDays: 60,
    amount: 459,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  advanced_90: {
    internalPlanType: "elite",
    neutralPlanCode: "advanced_90",
    durationDays: 90,
    amount: 649,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },

  // PROFESSIONAL (Escovia: Supreme)
  professional_1: {
    internalPlanType: "supreme",
    neutralPlanCode: "professional_1",
    durationDays: 1,
    amount: 49,
    currency: "chf",
    stripeLabel: "Premium visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  professional_2: {
    internalPlanType: "supreme",
    neutralPlanCode: "professional_2",
    durationDays: 2,
    amount: 79,
    currency: "chf",
    stripeLabel: "Premium visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  professional_3: {
    internalPlanType: "supreme",
    neutralPlanCode: "professional_3",
    durationDays: 3,
    amount: 109,
    currency: "chf",
    stripeLabel: "Premium visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  professional_4: {
    internalPlanType: "supreme",
    neutralPlanCode: "professional_4",
    durationDays: 4,
    amount: 129,
    currency: "chf",
    stripeLabel: "Premium visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  professional_5: {
    internalPlanType: "supreme",
    neutralPlanCode: "professional_5",
    durationDays: 5,
    amount: 149,
    currency: "chf",
    stripeLabel: "Premium visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  professional_7: {
    internalPlanType: "supreme",
    neutralPlanCode: "professional_7",
    durationDays: 7,
    amount: 179,
    currency: "chf",
    stripeLabel: "Premium visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  professional_14: {
    internalPlanType: "supreme",
    neutralPlanCode: "professional_14",
    durationDays: 14,
    amount: 259,
    currency: "chf",
    stripeLabel: "Premium visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  professional_20: {
    internalPlanType: "supreme",
    neutralPlanCode: "professional_20",
    durationDays: 20,
    amount: 299,
    currency: "chf",
    stripeLabel: "Premium visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  professional_25: {
    internalPlanType: "supreme",
    neutralPlanCode: "professional_25",
    durationDays: 25,
    amount: 329,
    currency: "chf",
    stripeLabel: "Premium visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  professional_30: {
    internalPlanType: "supreme",
    neutralPlanCode: "professional_30",
    durationDays: 30,
    amount: 349,
    currency: "chf",
    stripeLabel: "Premium visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  professional_60: {
    internalPlanType: "supreme",
    neutralPlanCode: "professional_60",
    durationDays: 60,
    amount: 649,
    currency: "chf",
    stripeLabel: "Premium visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  professional_90: {
    internalPlanType: "supreme",
    neutralPlanCode: "professional_90",
    durationDays: 90,
    amount: 899,
    currency: "chf",
    stripeLabel: "Premium visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
};

module.exports = { PLAN_CATALOG };