const PLAN_CATALOG = {
  // CLUB
  club_7: {
    planType: "club",
    durationDays: 7,
    amount: 29,
    currency: "chf",
    stripeLabel: "Digital visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  club_15: {
    planType: "club",
    durationDays: 15,
    amount: 49,
    currency: "chf",
    stripeLabel: "Digital visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  club_20: {
    planType: "club",
    durationDays: 20,
    amount: 59,
    currency: "chf",
    stripeLabel: "Digital visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  club_30: {
    planType: "club",
    durationDays: 30,
    amount: 89,
    currency: "chf",
    stripeLabel: "Digital visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  club_60: {
    planType: "club",
    durationDays: 60,
    amount: 169,
    currency: "chf",
    stripeLabel: "Digital visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  club_90: {
    planType: "club",
    durationDays: 90,
    amount: 239,
    currency: "chf",
    stripeLabel: "Digital visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  club_180: {
    planType: "club",
    durationDays: 180,
    amount: 449,
    currency: "chf",
    stripeLabel: "Digital visibility package",
    stripeDescription: "Online promotion and visibility service",
  },

  // PRIVILEGE
  privilege_7: {
    planType: "privilege",
    durationDays: 7,
    amount: 79,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  privilege_10: {
    planType: "privilege",
    durationDays: 10,
    amount: 99,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  privilege_15: {
    planType: "privilege",
    durationDays: 15,
    amount: 139,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  privilege_20: {
    planType: "privilege",
    durationDays: 20,
    amount: 169,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  privilege_30: {
    planType: "privilege",
    durationDays: 30,
    amount: 189,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  privilege_60: {
    planType: "privilege",
    durationDays: 60,
    amount: 349,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  privilege_90: {
    planType: "privilege",
    durationDays: 90,
    amount: 499,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },

  // ELITE
  elite_3: {
    planType: "elite",
    durationDays: 3,
    amount: 79,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  elite_5: {
    planType: "elite",
    durationDays: 5,
    amount: 99,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  elite_7: {
    planType: "elite",
    durationDays: 7,
    amount: 129,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  elite_10: {
    planType: "elite",
    durationDays: 10,
    amount: 149,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  elite_15: {
    planType: "elite",
    durationDays: 15,
    amount: 179,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  elite_20: {
    planType: "elite",
    durationDays: 20,
    amount: 209,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  elite_30: {
    planType: "elite",
    durationDays: 30,
    amount: 249,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  elite_60: {
    planType: "elite",
    durationDays: 60,
    amount: 459,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  elite_90: {
    planType: "elite",
    durationDays: 90,
    amount: 649,
    currency: "chf",
    stripeLabel: "Featured visibility package",
    stripeDescription: "Online promotion and visibility service",
  },

  // SUPREME
  supreme_1: {
    planType: "supreme",
    durationDays: 1,
    amount: 49,
    currency: "chf",
    stripeLabel: "Premium visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  supreme_2: {
    planType: "supreme",
    durationDays: 2,
    amount: 79,
    currency: "chf",
    stripeLabel: "Premium visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  supreme_3: {
    planType: "supreme",
    durationDays: 3,
    amount: 109,
    currency: "chf",
    stripeLabel: "Premium visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  supreme_4: {
    planType: "supreme",
    durationDays: 4,
    amount: 129,
    currency: "chf",
    stripeLabel: "Premium visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  supreme_5: {
    planType: "supreme",
    durationDays: 5,
    amount: 149,
    currency: "chf",
    stripeLabel: "Premium visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  supreme_7: {
    planType: "supreme",
    durationDays: 7,
    amount: 179,
    currency: "chf",
    stripeLabel: "Premium visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  supreme_14: {
    planType: "supreme",
    durationDays: 14,
    amount: 259,
    currency: "chf",
    stripeLabel: "Premium visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  supreme_20: {
    planType: "supreme",
    durationDays: 20,
    amount: 299,
    currency: "chf",
    stripeLabel: "Premium visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  supreme_25: {
    planType: "supreme",
    durationDays: 25,
    amount: 329,
    currency: "chf",
    stripeLabel: "Premium visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  supreme_30: {
    planType: "supreme",
    durationDays: 30,
    amount: 349,
    currency: "chf",
    stripeLabel: "Premium visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  supreme_60: {
    planType: "supreme",
    durationDays: 60,
    amount: 649,
    currency: "chf",
    stripeLabel: "Premium visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
  supreme_90: {
    planType: "supreme",
    durationDays: 90,
    amount: 899,
    currency: "chf",
    stripeLabel: "Premium visibility package",
    stripeDescription: "Online promotion and visibility service",
  },
};

module.exports = { PLAN_CATALOG };